---
title: "Data visualization practice"
format:
  html:
    code-fold: true
    code-summary: "Show code"
    embed-resources: true
execute:
  warning: false
  message: false
---

## Load packages
```{r}
library(readr)
library(here) # makes it easier to deal with file paths?
library(dplyr)
library(tidyr)
library(forcats) # for categorical data
library(janitor) # data wrangling i.e. clean_names !!

library(ggplot2)
library(plotly) # interactive graphics
library(DT)
library(leaflet)
```

```{r}
delta_visits_raw <- read_csv(here("data/Socioecological_monitoring_data.csv")) # here function of most utility in a quarto doc where working directories and relative paths can get funky
```

## Data exploration
```{r}
### Check out column names
colnames(delta_visits_raw)

### Peek at each column and class
glimpse(delta_visits_raw)

### From when to when
range(delta_visits_raw$Date)

### Which time of day?
unique(delta_visits_raw$Time_of_Day)
```

## Clean up the data

```{r}
delta_visits <- delta_visits_raw %>% 
  clean_names() #lowercase and snake_case all colnames
delta_visits
```

```{r}
visits_long <- delta_visits %>% 
  pivot_longer(
    col = c(sm_boat, med_boat, lrg_boat, bank_angler, scientist, cars),
    names_to = "visitor_type",
    values_to = "quantity"
  ) %>% 
  rename(restore_loc = eco_restore_approximate_location) %>% 
  select(-notes)
 glimpse(visits_long)
```

```{r}
daily_visits_loc <- visits_long %>% 
  group_by(restore_loc, date, visitor_type) %>% # doesn't change anything just creates a "flag" for next operation
  summarize(daily_visits = sum(quantity), .groups = "drop")
glimpse(daily_visits_loc)
```

## Data vis


```{r}
daily_visits_loc %>% # this construction allows us to modify the dataframe in-situ b4 plotting
  filter(daily_visits < 30,
  visitor_type %in% c("sm_boat", "lrg_boat")) %>% 
  ggplot(aes(x = restore_loc, y = daily_visits)) +
    geom_boxplot() + # or `violin()` or `col()` etc etc
    labs(title = "Plot title")

ggplot(data = daily_visits_loc,
       aes(x = restore_loc, y = daily_visits)) +
  geom_col(color = 'red',
           fill = "steelblue")
```

```{r}
daily_visits_loc %>% 
  ggplot(aes(y = restore_loc, x = daily_visits, fill = visitor_type)) + # flipping x and y order -> horizontal
  geom_col() +
  labs(x = "Number of visits",
       y = "Restoration location",
       fill = "Visitor type",
       title = "Total visits to the restoration areas",
       subtitle = "Sum of all visits between July and March 2018"
  ) + 
    scale_x_continuous(breaks = seq(0, 120, 20), expand = c(0, 0)) +
    theme_minimal() +
    theme(
      legend.position = "bottom",
      axis.ticks.y = element_blank()
    )

```


```{r}
daily_visits_totals <- daily_visits_loc %>%
  group_by(restore_loc) %>%
  mutate(total = sum(daily_visits)) %>%
  ungroup() %>%
  mutate(restore_loc = fct_reorder(restore_loc, desc(total)))

unique(daily_visits_totals$restore_loc)

facet_plot <- ggplot(data = daily_visits_totals,
       aes(x = visitor_type, y = daily_visits,
           fill = visitor_type)) +
    geom_col() +
    facet_wrap(~restore_loc,
               scales = "free_y", # so can be different per facet
               ncol   = 5,
               nrow   = 2) +
    scale_fill_viridis_d() +
    labs(x        = "Type of visitor",
         y        = "Number of Visits",
         title    = "Total Number of Visits to Delta Restoration Areas",
         subtitle = "Sum of all visits during study period") +
    theme_bw() +
    theme(legend.position = "bottom",
          axis.ticks.x    = element_blank(),
          axis.text.x     = element_blank())

facet_plot
```

### Make it interactive

```{r}
ggplotly(facet_plot, tooltip = c("x", "y"))

```

## Show an interactive table using DT
```{r}
datatable(delta_visits) # various options for how it displays
```
